### ISSUE TITLE
Firmado del xml delos documentos falla

### ISSUE THREAD

**Issue by FuriosoJack** [Stenfrank/ubl21dian#3]
Hola Frank, estuve revisando la manera en que firmas los documentos pero esta presentando una falla, al momento de firmarlos arroja errores de firma en el portal.

Yo junto a otro compañero desarrollamos para nuestra empresa la facturación v1 y estamos haciendo el desarrollo de la v2.1, yo me estoy encargando de la parte de firmado y envio. 
Actualmente estoy haciendo unas pruebas de firmar un documento de v1 con la clase **SignInvoice** pero al momento de revisar en la dian aparece el siguiente error, el cual es debido al error de firmado

` <ns3:Evento>Firma electrónica de un documento</ns3:Evento>
                        <ns3:FechaVeriTec>2019-08-15T16:38:11-05:00</ns3:FechaVeriTec>
                        <ns3:ReglaVeriTec>VALIDARFIRMA</ns3:ReglaVeriTec>
                        <ns3:PropiedadesTecnicas>
                            <ns3:PropiedadVeriTec>java.exception.msg</ns3:PropiedadVeriTec>
                            <ns3:DescripcionVeriTec>com.indra.mmdd.signature.exceptions.ValidateException:
                                xades4j.verification.ReferenceValueException: Reference
                                '#KEY-INFO-CD39D6D8FFAC9A99E9C8A4BF09951F66FA39C850' cannot be validated
                            </ns3:DescripcionVeriTec>
                        </ns3:PropiedadesTecnicas>`

Hago estas pruebas antes de comenzarlas en la version v2 para corroborar la firma, sin embargo quisiera que me aclaras si tu has probado dicha clase que firma las facturas en la V2.1 corroborando que la firma sea valida?.

**Comment by Stenfrank** [comment]
For the previous validation version, the signature is no longer supported by sha1 and the consumption of the Web Service is through a digital certificate
